### ISSUE TITLE
Add support for "STATE: RESERVED" for a CVE ?

### ISSUE THREAD

**Issue by aygupt1822** [vehemont/nvdlib#19]
I was querying with api and stumble across this CVE-2023-23605 record.

When I tried to query this CVE with `nvdlib.searchCVE(cveId="CVE-2023-23605")` the result was empty.

This should be resolved, if the STATE of CVE is set to "RESERVED" ?
Also link for this CVE : https://github.com/CVEProject/cvelist/blob/master/2023/23xxx/CVE-2023-23065.json

**Comment by vehemont** [comment]
Hi,

I agree reserved CVEs should not return empty and the user should be notified it is a reserved CVE. I will look into a good way of building that check into the current method. I will update NVDLib to a new version with this change soon.

Thanks for finding that!

**Comment by vehemont** [comment]
After further investigation, it seems this is expected behavior by the NVD API. When looking at the raw data of the `cveId` request for CVE-2023-23605, the NVD API does not include information if the CVE is reserved. This seems to be the correct response from the NVD API, but if you feel this is in error and the API should return `CVE_data_meta` to denote the CVE is reserved, I recommend emailing [nvd@nist.gov](mailto:nvd@nist.gov). They might be able to provide further insight why the API behaves this way or fix it. 

Here is the API query for CVE-2023-23605:
https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2023-23605
```
{"resultsPerPage":0,"startIndex":0,"totalResults":0,"format":"NVD_CVE","version":"2.0","timestamp":"2023-02-28T14:39:26.830","vulnerabilities":[]}
```

From the [NVD FAQ](https://nvd.nist.gov/general/FAQ-Sections/General-FAQs#:~:text=The%20NVD%20processes%20the%20CVE%20List%20every%20hour%20to%20ingest%20new%20CVE%20publications%2C%20rejections%2C%20or%20modifications.%20The%20NVD%20only%20contains%20CVEs%20that%20have%20been%20published%20to%20the%20Official%20CVE%20List.%20Any%20CVE%20that%20is%20still%20in%20a%20**RESERVED**%20state%20will%20not%20be%20ingested%20into%20the%20NVD.):
> The NVD processes the CVE List every hour to ingest new CVE publications, rejections, or modifications. The NVD only contains CVEs that have been published to the Official CVE List. Any CVE that is still in a **RESERVED** state will not be ingested into the NVD.

**Comment by aygupt1822** [comment]
Hello,

Thank you for the clarification. I will mail them and then lets see what happens.
