### ISSUE TITLE
Latest version of nvdlib-0.7.5-py3-none-any.whl no longer recognizes the 'timeout' parameter

### ISSUE THREAD

**Issue by johnlabuyfoy1024** [vehemont/nvdlib#31]
I noticed that the latest version of nvdlib-0.7.5-py3-none-any.whl no longer recognizes the 'timeout' parameter - was this intentional?

**Comment by vehemont** [comment]
Hi,

I believe the parameter you are referring to was a test that I made specifically for testing an issue here: https://github.com/vehemont/nvdlib/issues/26#issuecomment-1629429960

Since a 30 second timeout is sufficient, I didn't feel it was appropriate to include the parameter. There hasn't been any reports of a need for a longer/adjustable timeout, so the change to leave it out was intentional. If you do not utilize the `searchCVE_V2` call, then continuing to use that modified version of NVDLib 0.7.5 should not cause you any problems at this time. 

Thank you
