### ISSUE TITLE
Missing `startIndex` in searchCVE_V2()

### ISSUE THREAD

**Issue by BoxHezi** [vehemont/nvdlib#36]
Hi @vehemont, thanks for this wonderful library.

I've noticed that in `searchCVE_V2()` method.
At the NIST NVD Document, it has such parameter that can be passed in.
![image](https://github.com/vehemont/nvdlib/assets/15809407/655778f6-e0b7-400c-bd72-56334802e306)

Will this parameter be added?

---

One minor suggest:
How about adding `**kwargs` for the `searchCVE_V2()` method?

**Comment by vehemont** [comment]
Hi,

Could you please provide more details as to how the `startIndex` parameter could be used in `searchCVE_V2` ? A search is done starting at index 0 and completes once it has iterates through all of the indexes. It was purposely not added to make searching CVEs easier, to not have to worry about using `startIndex`. I am not sure how inserting a `startIndex` could be useful, but I am interested in hearing your thoughts behind this.

`**kwargs` defeats the purpose of NVDLib, in my opinion. NVDLib is meant to be a "training wheels" approach to utilizing the NVD API. It is an easy way to utilize the API by taking away the paging, delay, and parsing mechanics and making the results easier to obtain. Allowing any parameter to be sent through a request might introduce more frequent human error, and leave the user not understanding why their syntax is incorrect since the NVD API does not return helpful errors when sent incorrect syntax in a request.

Thank you creating this issue and speaking your thoughts,
vehemont

**Comment by BoxHezi** [comment]
Hi,

I am doing a project which try to get all CVEs in to a local database (e,g, one or multiple JSON files). In this case, when I am going to do incremental update, I will need a `startIndex` parameter. It's just one requirement that I notice when I am using this library. (Probably I am the only one who need this parameter)

Thanks for explaining the `**kwargs` idea, understand the idea to not have it. Thanks again for this beautiful library.
Box

**Comment by vehemont** [comment]
Hi,

I have given this some thought and I don't think adding `startIndex` is a direction I want to go. I think if you would like to control paging, interfacing with the NVD API directly without NVDLIb is a better option and will give you more control. If paging is added to NVDLib, it becomes a requests wrapper with extra baggage (NVDLib is treading that line already). I want NVDLib to be an easy entry into using the NVD API for anyone. If you or someone else would like to create a fork of NVDLib to allow that feature, I am in full support. 

I do appreciate your feedback, and if you have any other ideas please don't hesitate to open an issue. 

vehemont
