### ISSUE TITLE
Doc error for getting len() from nvdlib.searchCPE_V2

### ISSUE THREAD

**Issue by OlegAndrianov** [vehemont/nvdlib#47]
nvdlib.searchCPE_V2 does not produce list, so len() function can not be used.
Documentation has this example:

> r = nvdlib.searchCPE(lastModStartDate='2020-01-01 00:00', lastModEndDate='2020-02-01 00:00', keywordSearch='PHP')
> print(len(r))
> 
> 1599

But when i use nvdlib.searchCPE_V2, which i suspect is the proper way to do, i am getting _TypeError: object of type 'generator' has no len()_
At least documentation needs to be updated, i am not sure if making output a list is a possibility, but if that is possible i would certainly prefer to have a way to get a len from my results.

**Comment by vehemont** [comment]
Hi,

I see the predicament, but I feel it is not due to lack of documentation. The way search V2 works, it only pulls one CVE/CPE at a time using a _generator_. So using a `len()` operation is not very intuitive, and also as the error states `len()` is not supported on generator types. The original `searchCVE/CPE` function pulls ALL the CVE/CPEs at one time and automatically inserts them into a list, unlike search V2 that only iterates through one CVE/CPE at a time. I personally do not use V2 at all, but it has its place to [lower memory usage](https://github.com/vehemont/nvdlib/pull/24) when making large calls on resource constrained hosts.  
  
If you would like to continue using search V2 and also have the ability to call `len()`, I suggest using the search V2 function to append all the items into a list, which you can then call a `len()` function. Here is an example:  
  
```
>>> cveList = []
>>> r = nvdlib.searchCVE_V2(keywordSearch='Microsoft Exchange 2010', limit=100)
>>> for eachCVE in r:
...     cveList.append(eachCVE)
...
>>> len(cveList)
16
```

**Comment by OlegAndrianov** [comment]
Thanks, i just casted generator into list. Not sure if that can break anything. Regardless I suggest updating guidance to reflect that this will not work on V2.

**Comment by Olegandr** [comment]
I just read you comment and now i am confused beacause i do not see V2 returning 1 thing at a time, it clearly returns a bunch of entries are you saying the API calls to NIST are made several times when i iterate through generator?

**Comment by vehemont** [comment]
> I just read you comment again and now i am confused beacause i do not see V2 returning 1 thing at a time, it clearly returns a bunch of entries

The first [example](https://github.com/vehemont/nvdlib/issues/47#issuecomment-2305241851) I provided iterates through _all_ values in the generator. A generator is not aware of how big it is, that is why you can't call `len()` on a generator. I think I am paraphrasing heavily here - I am not a professional Python developer. It will only obtain the next value if it is called. You can also iterate through a generator one by one by using the `next()` built-in function. Here is an example of using the `next()` function to iterate through the generator one by one.

```
>>> r = nvdlib.searchCVE_V2(keywordSearch='Microsoft Exchange 2010', limit=100)
>>> next(r).id
'CVE-2010-1689'
>>> next(r).id
'CVE-2010-1690'
>>> next(r).id
'CVE-2010-3190'
```
Search V2 makes all the required calls to the NVD API then stores the response in a dictionary.  Once the generator is accessed/iterated (such as with the for loop in my first example, or `next()`) that is when the CVE in the raw response is converted into a CVE/CPE object, one CVE at a time. This is in contrast to the normal search function of converting the entire response and all items in the response to objects, which can be a bit more memory intensive, immediately after the call to the NVD API. 
  
Snippet from Search V2 showing only when the next value in the generator is called will it then convert the next CVE to an object:
https://github.com/vehemont/nvdlib/blob/c1f59e68fb2079e139ed7c70fc2b3adad12127ff/nvdlib/cve.py#L313-L317

**Comment by Olegandr** [comment]
> CVE/CPE in the raw response is converted into a CVE/CPE object, one item at a time
Ok, i see now, thank you.
