### ISSUE TITLE
Query from 2 September breaks parser

### ISSUE THREAD

**Issue by garikello3d** [vehemont/nvdlib#7]
Hi,

using latest `nvdlib` of 0.5.8.

When querying all records from 100 day depth, it breaks while parsing the data.

```
$ python
Python 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nvdlib
>>> import datetime
>>> end = datetime.datetime.now()
>>> start = end - datetime.timedelta(days=100)
>>> cves = nvdlib.searchCVE(pubStartDate=start, pubEndDate=end)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/nvdlib/cve.py", line 307, in searchCVE
    raw = __get('cve', parameters, limit, key, verbose)
  File "/usr/lib/python3.10/site-packages/nvdlib/get.py", line 65, in __get
    getData = requests.get(link, params=parameters, timeout=30).json()['result']['CVE_Items']
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by vehemont** [comment]
Hello,

Thank you for opening an issue for this bug. After some troubleshooting I was able to determine the failure was due to the encoding of the request. The `requests` module will perform a [best guess about the encoding of the response](https://requests.readthedocs.io/en/latest/user/quickstart/#:~:text=When%20you%20make%20a%20request%2C%20Requests%20makes%20educated%20guesses%20about%20the%20encoding%20of%20the%20response%20based%20on%20the%20HTTP%20headers.%20The%20text%20encoding%20guessed%20by%20Requests%20is%20used%20when%20you%20access%20r.text.%20You%20can%20find%20out%20what%20encoding%20Requests%20is%20using%2C%20and%20change%20it%2C%20using%20the%20r.encoding%20property%3A). In your particular `searchCVE` query the `requests` module was attempting to decode the response as ISO-8859-1, and not the required decoding of UTF8 as per the NVD API response.  

I have updated NVDLib to [0.5.9](https://github.com/vehemont/nvdlib/compare/v0.5.8...v0.5.9) to resolve this issue and statically set the expected encoding to `utf-8`, as well some other small improvements.

Please let me know if these change resolve the issue after updating your NVDLib module to the new 0.5.9 version.

**Comment by garikello3d** [comment]
Indeed, without an API key the service responds with 403 if you request more than ~60 days of history. After starting using the API key and upgrading to nvdlib 0.5.9, all errors have gone. I think we can close the issue. Thanks.

**Comment by vehemont** [comment]
Thanks for the clarification about the 403 error. I'm glad the new version resolved the issue.
